development:
  adapter: mysql2
  database: es_development
  username: root
  password: 123456
  host: 127.0.0.1
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  database: es_test
  username: root
  password: 123456
  host: 127.0.0.1
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  database: es_production
  username: root
  password: 123456
  host: 127.0.0.1
  socket: /tmp/mysql.sock